//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SREntities : DbContext
    {
        public SREntities()
            : base("name=SREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOG> LOGs { get; set; }
        public virtual DbSet<MEAL> MEALS { get; set; }
        public virtual DbSet<RATING> RATINGS { get; set; }
        public virtual DbSet<SR> SRs { get; set; }
        public virtual DbSet<SYS_MENU> SYS_MENU { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_DATA> USER_DATA { get; set; }
        public virtual DbSet<USER_RATING> USER_RATING { get; set; }
    }
}
