//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR
    {
        public int ID { get; set; }
        public string FoodName { get; set; }
        public string FoodIngredients { get; set; }
        public Nullable<int> NumberofIngredients { get; set; }
        public string FoodDescription { get; set; }
        public string ImgPath { get; set; }
    }
}
