//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENU
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ActionName { get; set; }
        public string Controller { get; set; }
        public string Pershkrimi { get; set; }
        public string HtmlClass { get; set; }
        public Nullable<int> Renditja { get; set; }
    }
}
