//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DATA
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public Nullable<decimal> BloodGlucose { get; set; }
        public Nullable<bool> HasDiabet { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
