//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RATING
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int RatingID { get; set; }
        public int MealID { get; set; }
    
        public virtual MEAL MEAL { get; set; }
        public virtual RATING RATING { get; set; }
        public virtual USER USER { get; set; }
    }
}
